### PR TITLE
lz4: add vgo support

### PR DESCRIPTION
**Pull request by sbinet**

### CODE REVIEW

**Comment by sbinet** [comment]
vgo-compat support isn't in Go-1.8.x (and probably won't...), thus the build failure for only `go-1.8.x` in travis.

**Comment by pierrec** [comment]
I am in favor of adding vgo support but then the support for 1.8 needs to be dropped. Any objection?

**Comment by sbinet** [comment]
For my projects, I think I will wait for 1.11 before dropping support for 1.8.x.

I just provided the PR so as to reduce duplicated work :)

**Comment by sbinet** [comment]
I guess we could consider merging this in, now that Go1.11 is out :)

**Comment by sbinet** [comment]
strictly speaking, 883bdb7 isn't necessary.
I could just drop it on the floor, if requested.

PTAL.

**Comment by sbinet** [comment]
done. PTAL.

**Comment by pierrec** [comment]
Merci!

**Comment by sbinet** [comment]
thanks! could you tag it? (so `GO111MODULE=on go mod tidy` can find the new version)

thanks again.

**Comment by sbinet** [comment]
apologies for being a pain in the neck...
but it seems to me you tagged `v2.0.5` at the same position than `v2.0.4` :)

```
*   68a7290 (HEAD -> master, origin/master, origin/HEAD) Merge pull request #26 from sbinet-staging/vgo-support
|\  
| * 0032ab8 lz4: enable tests with and w/o modules
| * aad00d9 lz4: add Go1.11, drop Go1.8
| * 736b6e0 lz4: add support for Go modules
|/  
* ea73140 (tag: v2.0.5, tag: v2.0.4) perf improvements: removed default unused debug args evaluations; faster writer for short writes
* dbe9298 #31: updated README to be clearer about LZ4 compatibility
* 1958fd8 (tag: v2.0.3) xxh32zero: fixed invalid initialization (fixes #27)
```

**Comment by pierrec** [comment]
You are right, sorry. Unfortunately, this change has stirred up a few reactions are some people do not have access to go versions with module support.
I am considering rolling it back.

**Comment by sbinet** [comment]
ok. theoretically, as long as the Go version is >=1.9.x or >= 1.10.y (where x>=7, y>=4), it should work.
even w/o enabling proper module mode.

**Comment by pierrec** [comment]
And indeed it does. The issue though is that some platforms do not provide those (relatively) new versions of go. People are still using 1.10.1 or 1.9.4. See #33.

**Comment by sbinet** [comment]
fair enough.

**Pull request merged**
